name: anity
description: Fixed minimal app for anime list
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true